from django.utils import timezone


def header(app, *middle):
    now = timezone.now().strftime('%Y-%m-%d %H:%M')
    tz = timezone.now().tzinfo

    header_lines = [
        f' * Generated by RxDjango on {now} ({tz})',
    ] + [
        f' * {line}' for line in middle
    ]

    footer_lines = [
        ' * To rebuild it, run:',
        f' *     ./manage.py makefrontend [{app}]',
    ]

    warning = 'DO NOT EDIT THIS FILE'

    length = max(len(line) for line in header_lines)
    w_left = int((length - len(warning)) / 2)
    w_right = length - len(warning) - w_left - 1

    header_lines = [
        line + ' ' * (length - len(line) + 1) + '*'
        for line in header_lines
    ]
    header_lines.append(
        ' *' + ' ' * w_left + warning + ' ' * w_right + '*',
    )

    footer_lines = [
        line + ' ' * (length - len(line) + 1) + '*'
        for line in footer_lines
    ]

    code = ['/*' + '*' * length]
    for line in header_lines:
        code.append(line)
        code.append(' *' + ' ' * (length - 1) + '*')

    for line in footer_lines:
        code.append(line)
        code.append(' *' + ' ' * (length - 1) + '*')

    code.append(' ' + '*' * length + '*/')

    return code
