"""Generate example page React components from MyST docs.

Reads `docs/examples/index.md` for ordering and `docs/examples/<slug>.md`
for each page, then writes:

  - examples/frontend/src/app/examples/<slug>/<Pascal>Page.tsx
  - examples/frontend/src/app/examples/pages.generated.ts

Docs are the single source of truth: title, description, and section
contents (backend/frontend `literalinclude` blocks) drive the output.
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs" / "examples"
PAGES_DIR = REPO_ROOT / "examples" / "frontend" / "src" / "app" / "examples"

GENERATED_HEADER = (
    "// @generated by tools/docgen — do not edit.\n"
    "// Source: docs/examples/{source}\n"
)

BACKEND_PREFIX = "../../examples/backend/"
FRONTEND_PREFIX = "../../examples/frontend/src/app/examples/"


@dataclass
class Section:
    name: str           # e.g. "Backend"
    include_path: str   # raw literalinclude path
    source_path: str    # path passed to <SourceFile path=...>
    is_frontend: bool


@dataclass
class Page:
    slug: str           # e.g. "authorization_meta"
    title: str          # e.g. "Authorization Meta"
    description: str
    sections: list[Section]


def pascal(slug: str) -> str:
    return "".join(part.capitalize() for part in slug.split("_"))


def kebab(slug: str) -> str:
    return slug.replace("_", "-")


def strip_inline_markdown(text: str) -> str:
    # Collapse newlines/whitespace into single spaces, strip inline code backticks.
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"`([^`]*)`", r"\1", text)
    return text


def parse_index_order(index_md: Path) -> list[str]:
    lines = index_md.read_text(encoding="utf-8").splitlines()
    order: list[str] = []
    in_toctree = False
    for line in lines:
        stripped = line.strip()
        if stripped.startswith("```{toctree}"):
            in_toctree = True
            continue
        if in_toctree:
            if stripped.startswith("```"):
                break
            if not stripped or stripped.startswith(":"):
                continue
            order.append(stripped)
    if not order:
        raise SystemExit(f"No toctree entries found in {index_md}")
    return order


def parse_section_body(body: str) -> str | None:
    # Find a `{literalinclude} <path>` directive (fenced or colon-fenced).
    m = re.search(
        r"(?:```|:::)\s*\{literalinclude\}\s+(\S+)",
        body,
    )
    return m.group(1) if m else None


def classify_section(include_path: str) -> tuple[str, bool]:
    if include_path.startswith(FRONTEND_PREFIX):
        return include_path[len(FRONTEND_PREFIX):], True
    if include_path.startswith(BACKEND_PREFIX):
        return include_path[len(BACKEND_PREFIX):], False
    # Fallback: keep as-is; not frontend.
    return include_path, False


def parse_page(slug: str, md_path: Path) -> Page:
    text = md_path.read_text(encoding="utf-8")

    # Title: first `# ...` line.
    m_title = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    if not m_title:
        raise SystemExit(f"No H1 title in {md_path}")
    title = m_title.group(1).strip()

    after_title = text[m_title.end():]

    # Split remainder on `## Heading` lines.
    parts = re.split(r"^##\s+(.+?)\s*$", after_title, flags=re.MULTILINE)
    # parts[0] = description body; then pairs (heading, body), (heading, body)…
    description = strip_inline_markdown(parts[0])

    sections: list[Section] = []
    for i in range(1, len(parts), 2):
        name = parts[i].strip()
        body = parts[i + 1] if (i + 1) < len(parts) else ""
        include_path = parse_section_body(body)
        if include_path is None:
            # Skip sections without a literalinclude (unsupported for now).
            continue
        source_path, is_frontend = classify_section(include_path)
        sections.append(
            Section(
                name=name,
                include_path=include_path,
                source_path=source_path,
                is_frontend=is_frontend,
            )
        )

    if not sections:
        raise SystemExit(f"No sections with literalinclude in {md_path}")

    return Page(slug=slug, title=title, description=description, sections=sections)


def render_page_tsx(page: Page) -> str:
    pascal_name = pascal(page.slug)
    kebab_slug = kebab(page.slug)
    demo_component = f"{pascal_name}Demo"
    page_component = f"{pascal_name}Page"

    needs_badge = any(s.is_frontend for s in page.sections)

    imports_layout = [
        "ExampleLayout",
        "ExampleSection",
        "ExampleSectionHeading",
        "ExampleDescription",
    ]
    if needs_badge:
        imports_layout.append("ExampleClientBadge")

    lines: list[str] = []
    lines.append(GENERATED_HEADER.format(source=f"{page.slug}.md"))
    lines.append("import React from 'react';")
    lines.append(f"import {{ {demo_component} }} from './demo';")
    lines.append("import {")
    for name in imports_layout:
        lines.append(f"  {name},")
    lines.append("} from '../../components/ExampleLayout';")
    lines.append("import { SourceFile } from '../../components/SourceFile';")
    lines.append("")
    lines.append(f"export function {page_component}() {{")
    lines.append(f"  return (")
    lines.append(
        f"    <ExampleLayout title=\"{page.title}\" demo={{<{demo_component} />}}>"
    )

    # Description section (first).
    lines.append('      <ExampleSection position="first">')
    lines.append("        <ExampleDescription>")
    lines.append(f"          {page.description}")
    lines.append("        </ExampleDescription>")
    lines.append("      </ExampleSection>")

    # Content sections.
    last_index = len(page.sections) - 1
    for idx, section in enumerate(page.sections):
        section_id = f"{kebab_slug}-{section.name.lower().replace(' ', '-')}"
        attrs = [f'ariaLabelledBy="{section_id}"']
        if idx == last_index:
            attrs.append('position="last"')
        attrs_str = " ".join(attrs)
        lines.append(f"      <ExampleSection {attrs_str}>")

        if section.is_frontend:
            lines.append(
                "        <div className=\"flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between\">"
            )
            lines.append(
                f"          <ExampleSectionHeading id=\"{section_id}\">"
            )
            lines.append(f"            {section.name}")
            lines.append("          </ExampleSectionHeading>")
            lines.append("          <ExampleClientBadge />")
            lines.append("        </div>")
        else:
            lines.append(f"        <ExampleSectionHeading id=\"{section_id}\">")
            lines.append(f"          {section.name}")
            lines.append("        </ExampleSectionHeading>")

        lines.append(f"        <SourceFile path=\"{section.source_path}\" />")
        lines.append("      </ExampleSection>")

    lines.append("    </ExampleLayout>")
    lines.append("  );")
    lines.append("}")
    lines.append("")
    lines.append(f"export default {page_component};")
    lines.append("")
    return "\n".join(lines)


def render_registry_ts(pages: list[Page]) -> str:
    lines: list[str] = []
    lines.append("// @generated by tools/docgen — do not edit.")
    lines.append("// Source: docs/examples/index.md (toctree order)")
    lines.append("import type { ReactElement } from 'react';")
    for page in pages:
        pascal_name = pascal(page.slug)
        lines.append(
            f"import {{ {pascal_name}Page }} from './{page.slug}/{pascal_name}Page';"
        )
        lines.append(
            f"import {{ {pascal_name}Demo }} from './{page.slug}/demo';"
        )
    lines.append("")
    lines.append(
        "export type Page = [app: string, title: string, Component: () => ReactElement, Demo: () => ReactElement];"
    )
    lines.append("")
    lines.append("export const pages: Page[] = [")
    for page in pages:
        pascal_name = pascal(page.slug)
        lines.append(
            f"  ['{page.slug}', '{page.title}', {pascal_name}Page, {pascal_name}Demo],"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def main() -> int:
    order = parse_index_order(DOCS_DIR / "index.md")
    pages: list[Page] = []
    for slug in order:
        md_path = DOCS_DIR / f"{slug}.md"
        if not md_path.exists():
            raise SystemExit(f"Missing doc for slug '{slug}': {md_path}")
        pages.append(parse_page(slug, md_path))

    written = 0
    for page in pages:
        target = PAGES_DIR / page.slug / f"{pascal(page.slug)}Page.tsx"
        if write_if_changed(target, render_page_tsx(page)):
            written += 1
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    registry = PAGES_DIR / "pages.generated.ts"
    if write_if_changed(registry, render_registry_ts(pages)):
        written += 1
        print(f"wrote {registry.relative_to(REPO_ROOT)}")

    print(f"docgen: {len(pages)} page(s), {written} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
