"""Generate React page components and the page registry from MyST docs.

Walks `docs/` recursively. For each `.md` file (except the root
`index.md`), produces a React page component, then writes a flat
hierarchical registry consumed by `Main.tsx`.

Pages with a ```{rxdemo} <app>``` directive get the example layout
(prose + demo iframe column). Pages without the directive get a plain
prose layout.

Output layout:
  - examples/frontend/src/app/examples/<app>/<Pascal>Page.tsx
        (only when the page has rxdemo; demo.tsx is hand-written and
         already lives alongside)
  - examples/frontend/src/app/pages/<slug-as-path>/Page.tsx
        (every non-demo page)
  - examples/frontend/src/app/pages.generated.ts (registry)
"""

from __future__ import annotations

import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
FRONTEND_APP = REPO_ROOT / "examples" / "frontend" / "src" / "app"
EXAMPLES_OUT = FRONTEND_APP / "examples"
PAGES_OUT = FRONTEND_APP / "pages"
REGISTRY_OUT = FRONTEND_APP / "pages.generated.ts"

# Subdirectories of docs/ that are NOT part of the user-facing site.
DOCS_SKIP_DIRS = {"adr", "rfcs", "dev"}

BACKEND_PREFIX = "../../examples/backend/"
FRONTEND_PREFIX = "../../examples/frontend/src/app/examples/"

GENERATED_HEADER = (
    "// @generated by tools/docgen — do not edit.\n"
    "// Source: docs/{source}\n"
)


@dataclass
class Section:
    name: str
    include_path: str
    source_path: str
    is_frontend: bool


@dataclass
class Page:
    slug: str           # path-style: 'overview' | 'examples' | 'examples/counter'
    title: str
    description: str
    rxdemo: str | None  # app name if {rxdemo} directive is present
    sections: list[Section] = field(default_factory=list)
    toctree: list[str] = field(default_factory=list)  # child slugs (relative to this page)
    source_md: str = ""  # relative path under docs/

    @property
    def parent(self) -> str | None:
        if "/" not in self.slug:
            return None
        return self.slug.rsplit("/", 1)[0]

    @property
    def depth(self) -> int:
        return self.slug.count("/")


def pascal(slug: str) -> str:
    parts = re.split(r"[/_-]", slug)
    return "".join(p.capitalize() for p in parts if p)


def kebab(slug: str) -> str:
    return slug.replace("_", "-").replace("/", "-")


def strip_inline_markdown(text: str) -> str:
    text = re.sub(r"\s+", " ", text).strip()
    text = re.sub(r"`([^`]*)`", r"\1", text)
    return text


def js_string(value: str) -> str:
    return value.replace("\\", "\\\\").replace("'", "\\'")


def classify_section(include_path: str) -> tuple[str, bool]:
    if include_path.startswith(FRONTEND_PREFIX):
        return include_path[len(FRONTEND_PREFIX):], True
    if include_path.startswith(BACKEND_PREFIX):
        return include_path[len(BACKEND_PREFIX):], False
    return include_path, False


def parse_literalinclude(body: str) -> str | None:
    m = re.search(r"(?:```|:::)\s*\{literalinclude\}\s+(\S+)", body)
    return m.group(1) if m else None


def parse_rxdemo(text: str) -> str | None:
    m = re.search(r"(?:```|:::)\s*\{rxdemo\}\s+(\S+)", text)
    return m.group(1) if m else None


def parse_toctree(text: str) -> list[str]:
    out: list[str] = []
    for m in re.finditer(r"(?:```|:::)\s*\{toctree\}([\s\S]*?)(?:```|:::)", text):
        body = m.group(1)
        for line in body.splitlines():
            s = line.strip()
            if not s or s.startswith(":"):
                continue
            out.append(s)
    return out


def slug_from_path(rel: Path) -> str:
    parts = list(rel.with_suffix("").parts)
    if parts and parts[-1] == "index":
        parts = parts[:-1]
    return "/".join(parts)


def parse_page(rel_md: Path, abs_md: Path) -> Page | None:
    text = abs_md.read_text(encoding="utf-8")
    slug = slug_from_path(rel_md)
    if slug == "":
        return None  # the root index.md is the home page, not a generated page

    m_title = re.search(r"^#\s+(.+?)\s*$", text, re.MULTILINE)
    if not m_title:
        raise SystemExit(f"No H1 title in {rel_md}")
    title = m_title.group(1).strip()
    after_title = text[m_title.end():]

    rxdemo = parse_rxdemo(after_title)
    toctree = parse_toctree(after_title)

    # Strip directive blocks so the description is just prose.
    stripped = re.sub(r"(?:```|:::)\s*\{[^}]+\}[\s\S]*?(?:```|:::)", "", after_title)
    parts = re.split(r"^##\s+(.+?)\s*$", stripped, flags=re.MULTILINE)
    description = strip_inline_markdown(parts[0])

    sections: list[Section] = []
    # Re-split on the original text to find literalinclude under each H2.
    raw_parts = re.split(r"^##\s+(.+?)\s*$", after_title, flags=re.MULTILINE)
    for i in range(1, len(raw_parts), 2):
        name = raw_parts[i].strip()
        body = raw_parts[i + 1] if (i + 1) < len(raw_parts) else ""
        include_path = parse_literalinclude(body)
        if include_path is None:
            continue
        source_path, is_frontend = classify_section(include_path)
        sections.append(Section(name, include_path, source_path, is_frontend))

    return Page(
        slug=slug,
        title=title,
        description=description,
        rxdemo=rxdemo,
        sections=sections,
        toctree=toctree,
        source_md=str(rel_md),
    )


def discover_pages() -> list[Page]:
    """Discover pages by walking toctrees from the root index.

    Only pages reachable from `docs/index.md` (transitively, through
    nested toctrees) are emitted. Loose `.md` files in `docs/` that
    are not linked from any toctree are ignored.
    """
    pages: list[Page] = []
    seen: set[str] = set()

    def walk(slug: str) -> None:
        if slug in seen:
            return
        # Resolve the markdown path for this slug.
        candidates = [
            DOCS_DIR / f"{slug}.md" if slug else None,
            DOCS_DIR / slug / "index.md" if slug else DOCS_DIR / "index.md",
        ]
        md_path: Path | None = None
        for c in candidates:
            if c is not None and c.exists():
                md_path = c
                break
        if md_path is None:
            return
        rel = md_path.relative_to(DOCS_DIR)
        seen.add(slug)
        page = parse_page(rel, md_path)
        if page is not None:
            pages.append(page)
            for entry in page.toctree:
                entry_clean = entry.replace(".md", "")
                if entry_clean.endswith("/index"):
                    entry_clean = entry_clean[: -len("/index")]
                child_slug = f"{slug}/{entry_clean}" if slug else entry_clean
                walk(child_slug)
        else:
            # Root index has no Page object but its toctree drives discovery.
            text = md_path.read_text(encoding="utf-8")
            for entry in parse_toctree(text):
                entry_clean = entry.replace(".md", "")
                if entry_clean.endswith("/index"):
                    entry_clean = entry_clean[: -len("/index")]
                walk(entry_clean)

    walk("")
    return pages


def order_pages(pages: list[Page]) -> list[Page]:
    """Order pages so the root toctree drives top-level order and each
    parent's toctree drives its children's order. Pages not referenced
    fall back to alphabetical at the end of their level."""
    by_slug = {p.slug: p for p in pages}

    root_index = DOCS_DIR / "index.md"
    root_order: list[str] = []
    if root_index.exists():
        root_order = parse_toctree(root_index.read_text(encoding="utf-8"))

    def resolve_child_slugs(parent: Page) -> list[str]:
        out: list[str] = []
        base = parent.slug
        for entry in parent.toctree:
            # entry may be a sibling file name; resolve relative to parent dir.
            entry_clean = entry.replace(".md", "")
            if entry_clean.endswith("/index"):
                entry_clean = entry_clean[: -len("/index")]
            cand = f"{base}/{entry_clean}" if base else entry_clean
            if cand in by_slug:
                out.append(cand)
        return out

    ordered: list[Page] = []
    seen: set[str] = set()

    def emit(slug: str) -> None:
        if slug in seen or slug not in by_slug:
            return
        page = by_slug[slug]
        seen.add(slug)
        ordered.append(page)
        for child_slug in resolve_child_slugs(page):
            emit(child_slug)

    # Top level: use root index toctree order.
    for entry in root_order:
        entry_clean = entry.replace(".md", "")
        if entry_clean.endswith("/index"):
            entry_clean = entry_clean[: -len("/index")]
        emit(entry_clean)

    # Anything left, alphabetical.
    for p in pages:
        if p.slug not in seen:
            emit(p.slug)

    return ordered


# ---------------------------------------------------------------------------
# Render: example page (has rxdemo)
# ---------------------------------------------------------------------------


def render_example_page_tsx(page: Page) -> str:
    assert page.rxdemo is not None
    app = page.rxdemo
    pascal_name = pascal(page.slug.split("/")[-1])
    kebab_slug = kebab(page.slug)
    demo_component = f"{pascal(app)}Demo"
    page_component = f"{pascal_name}Page"

    needs_badge = any(s.is_frontend for s in page.sections)

    imports_layout = [
        "ExampleLayout",
        "ExampleSection",
        "ExampleSectionHeading",
        "ExampleDescription",
    ]
    if needs_badge:
        imports_layout.append("ExampleClientBadge")

    lines: list[str] = []
    lines.append(GENERATED_HEADER.format(source=page.source_md))
    lines.append("import React from 'react';")
    lines.append(f"import {{ {demo_component} }} from './demo';")
    lines.append("import {")
    for name in imports_layout:
        lines.append(f"  {name},")
    lines.append("} from '../../components/ExampleLayout';")
    lines.append("import { SourceFile } from '../../components/SourceFile';")
    lines.append("")
    lines.append(f"export function {page_component}() {{")
    lines.append("  return (")
    lines.append(
        f"    <ExampleLayout title=\"{page.title}\" demo={{<{demo_component} />}}>"
    )

    lines.append('      <ExampleSection position="first">')
    lines.append("        <ExampleDescription>")
    lines.append(f"          {page.description}")
    lines.append("        </ExampleDescription>")
    lines.append("      </ExampleSection>")

    last_index = len(page.sections) - 1
    for idx, section in enumerate(page.sections):
        section_id = f"{kebab_slug}-{section.name.lower().replace(' ', '-')}"
        attrs = [f'ariaLabelledBy="{section_id}"']
        if idx == last_index:
            attrs.append('position="last"')
        attrs_str = " ".join(attrs)
        lines.append(f"      <ExampleSection {attrs_str}>")

        if section.is_frontend:
            lines.append(
                "        <div className=\"flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between\">"
            )
            lines.append(
                f"          <ExampleSectionHeading id=\"{section_id}\">"
            )
            lines.append(f"            {section.name}")
            lines.append("          </ExampleSectionHeading>")
            lines.append("          <ExampleClientBadge />")
            lines.append("        </div>")
        else:
            lines.append(f"        <ExampleSectionHeading id=\"{section_id}\">")
            lines.append(f"          {section.name}")
            lines.append("        </ExampleSectionHeading>")

        lines.append(f"        <SourceFile path=\"{section.source_path}\" />")
        lines.append("      </ExampleSection>")

    lines.append("    </ExampleLayout>")
    lines.append("  );")
    lines.append("}")
    lines.append("")
    lines.append(f"export default {page_component};")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Render: plain doc page (no rxdemo)
# ---------------------------------------------------------------------------


def resolve_toctree_slugs(page: Page, all_slugs: set[str]) -> list[str]:
    out: list[str] = []
    for entry in page.toctree:
        entry_clean = entry.replace(".md", "")
        if entry_clean.endswith("/index"):
            entry_clean = entry_clean[: -len("/index")]
        cand = f"{page.slug}/{entry_clean}" if page.slug else entry_clean
        if cand in all_slugs:
            out.append(cand)
    return out


def render_doc_page_tsx(page: Page, all_pages: list[Page]) -> str:
    page_component = f"{pascal(page.slug.split('/')[-1] or 'home')}Page"
    all_slugs = {p.slug for p in all_pages}
    children = resolve_toctree_slugs(page, all_slugs)
    title_by_slug = {p.slug: p.title for p in all_pages}

    lines: list[str] = []
    lines.append(GENERATED_HEADER.format(source=page.source_md))
    lines.append("import React from 'react';")
    lines.append("")
    lines.append(f"export function {page_component}() {{")
    lines.append("  return (")
    lines.append(
        "    <div className=\"mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10\">"
    )
    lines.append(
        f"      <h1 className=\"text-2xl font-semibold tracking-tight text-ink\">"
    )
    lines.append(f"        {page.title}")
    lines.append("      </h1>")
    if page.description:
        lines.append(
            "      <p className=\"mt-4 max-w-prose text-base leading-relaxed text-primary-800\">"
        )
        lines.append(f"        {page.description}")
        lines.append("      </p>")
    if children:
        lines.append("      <ul className=\"mt-6 flex flex-col gap-2\">")
        for child_slug in children:
            child_title = title_by_slug.get(child_slug, child_slug)
            lines.append("        <li>")
            lines.append(
                f"          <a href=\"/{child_slug}\" className=\"text-primary-700 hover:underline\">"
            )
            lines.append(f"            {child_title}")
            lines.append("          </a>")
            lines.append("        </li>")
        lines.append("      </ul>")
    lines.append("    </div>")
    lines.append("  );")
    lines.append("}")
    lines.append("")
    lines.append(f"export default {page_component};")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Render: registry
# ---------------------------------------------------------------------------


def example_page_path(page: Page) -> Path:
    # app/examples/<app>/<Pascal>Page.tsx
    assert page.rxdemo is not None
    pascal_name = pascal(page.slug.split("/")[-1])
    return EXAMPLES_OUT / page.rxdemo / f"{pascal_name}Page.tsx"


def doc_page_path(page: Page) -> Path:
    # app/pages/<slug>/Page.tsx
    return PAGES_OUT / page.slug / "Page.tsx"


def import_specifier(target: Path) -> str:
    rel = target.relative_to(FRONTEND_APP).with_suffix("")
    return "./" + str(rel)


def pascal_alias(page: Page) -> str:
    # Unique alias for non-demo page imports based on full slug.
    return pascal(page.slug.replace("/", "_")) + "Page"


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists() and path.read_text(encoding="utf-8") == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return True


def render_registry_ts(pages: list[Page]) -> str:
    lines: list[str] = []
    lines.append("// @generated by tools/docgen — do not edit.")
    lines.append("// Source: docs/")
    lines.append("import type { ReactElement } from 'react';")

    for page in pages:
        alias = pascal_alias(page)
        if page.rxdemo:
            local = f"{pascal(page.slug.split('/')[-1])}Page"
            lines.append(
                f"import {{ {local} as {alias} }} from '{import_specifier(example_page_path(page))}';"
            )
            lines.append(
                f"import {{ {pascal(page.rxdemo)}Demo }} from './examples/{page.rxdemo}/demo';"
            )
        else:
            local = f"{pascal(page.slug.split('/')[-1] or 'home')}Page"
            lines.append(
                f"import {{ {local} as {alias} }} from '{import_specifier(doc_page_path(page))}';"
            )
    lines.append("")
    lines.append("export type Page = {")
    lines.append("  slug: string;")
    lines.append("  title: string;")
    lines.append("  depth: number;")
    lines.append("  parent: string | null;")
    lines.append("  Component: () => ReactElement;")
    lines.append("  Demo: (() => ReactElement) | null;")
    lines.append("};")
    lines.append("")
    lines.append("export const pages: Page[] = [")
    for page in pages:
        parent_repr = "null" if page.parent is None else f"'{js_string(page.parent)}'"
        component = pascal_alias(page)
        demo = f"{pascal(page.rxdemo)}Demo" if page.rxdemo else "null"
        lines.append(
            "  { "
            f"slug: '{js_string(page.slug)}', "
            f"title: '{js_string(page.title)}', "
            f"depth: {page.depth}, "
            f"parent: {parent_repr}, "
            f"Component: {component}, "
            f"Demo: {demo}"
            " },"
        )
    lines.append("];")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    raw_pages = discover_pages()
    pages = order_pages(raw_pages)

    written = 0
    for page in pages:
        if page.rxdemo:
            target = example_page_path(page)
            content = render_example_page_tsx(page)
        else:
            target = doc_page_path(page)
            content = render_doc_page_tsx(page, pages)
        if write_if_changed(target, content):
            written += 1
            print(f"wrote {target.relative_to(REPO_ROOT)}")

    if write_if_changed(REGISTRY_OUT, render_registry_ts(pages)):
        written += 1
        print(f"wrote {REGISTRY_OUT.relative_to(REPO_ROOT)}")

    print(f"docgen: {len(pages)} page(s), {written} file(s) updated")
    return 0


if __name__ == "__main__":
    sys.exit(main())
