// @generated by tools/docgen — do not edit.
// Source: docs/examples/index.md

import React from 'react';

export function ExamplesPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Examples
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        A collection of small examples that show how RxDjango keeps a React UI in sync with a Django backend through reactive channels. Pick an example to see it in action.
      </p>
      <ul className="mt-6 flex flex-col gap-2">
        <li>
          <a href="/examples/counter" className="text-primary-700 hover:underline">
            Counter
          </a>
        </li>
        <li>
          <a href="/examples/carousel" className="text-primary-700 hover:underline">
            Carousel
          </a>
        </li>
        <li>
          <a href="/examples/memo" className="text-primary-700 hover:underline">
            Memo
          </a>
        </li>
        <li>
          <a href="/examples/authorization" className="text-primary-700 hover:underline">
            Authorization
          </a>
        </li>
        <li>
          <a href="/examples/authorization_meta" className="text-primary-700 hover:underline">
            Authorization Meta
          </a>
        </li>
      </ul>
    </div>
  );
}

export default ExamplesPage;
