// @generated by tools/docgen — do not edit.
// Source: docs/examples/task_board.md

import React from 'react';
import { TaskBoardDemo } from './demo';
import {
  ExampleLayout,
  ExampleSection,
  ExampleSectionHeading,
  ExampleDescription,
  ExampleClientBadge,
} from '../../components/ExampleLayout';
import { SourceFile } from '../../components/SourceFile';

export function TaskBoardPage() {
  return (
    <ExampleLayout title="Task board" demo={<TaskBoardDemo />}>
      <ExampleSection position="first">
        <ExampleDescription>
          Demonstrates the routed (live) tier of the queryset-list architecture (ADR-0018): tasks declares routing='project_id' -- a one-word column sugar that turns the field into a **live** list. A task created under a watched project, or moved into it, is delivered as it happens: no rebind, unlike [Static list](static_list)'s unrouted tier, whose one deliverable limitation is exactly this -- a new row waits for a rebind to appear. Moving a task to another project delivers the leave signal live too: the old side of the move disqualifies the row from the connection watching it, through an ordinary update frame. Routing is a security boundary, not a convenience: a connection receives every event whose publish() values intersect its own subscribe() values, and nothing else -- delivery *is* authorization here, while any filter condition left out of the routing dimension (a residual, like this example's status='open') is mere presentation, evaluated client-side and shipped with its value visible, so secrets must never live in a residual. The explicit, deliberately loud firehose for "no narrowing at all" is routing=BroadcastRouter() -- greppable by design, so a security review of routing code never has to guess which fields opted out of precise delivery.
        </ExampleDescription>
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-task-board-backend">
        <ExampleSectionHeading id="examples-task-board-backend">
          Backend
        </ExampleSectionHeading>
        <SourceFile path="task_board/channels.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-task-board-models">
        <ExampleSectionHeading id="examples-task-board-models">
          Models
        </ExampleSectionHeading>
        <SourceFile path="task_board/models.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-task-board-serializers">
        <ExampleSectionHeading id="examples-task-board-serializers">
          Serializers
        </ExampleSectionHeading>
        <SourceFile path="task_board/serializers.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-task-board-frontend" position="last">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <ExampleSectionHeading id="examples-task-board-frontend">
            Frontend
          </ExampleSectionHeading>
          <ExampleClientBadge />
        </div>
        <SourceFile path="task_board/demo.tsx" />
      </ExampleSection>
    </ExampleLayout>
  );
}

export default TaskBoardPage;
