/******************************************************
 * Generated by RxDjango on 2026-05-14 19:42 (UTC)    *
 *                                                    *
 * Based on serializers used by nested_model.channels *
 *                                                    *
 *                DO NOT EDIT THIS FILE               *
 *                                                    *
 * To rebuild it, run:                                *
 *                                                    *
 *     ./manage.py makefrontend [nested_model]        *
 *                                                    *
 ******************************************************/

export interface User {
  id: number;
  name: string;
  company: Company;
}

export interface Company {
  id: number;
  name: string;
}