/******************************************************
 * Generated by RxDjango on 2026-07-14 15:45 (UTC)    *
 *                                                    *
 * Based on serializers used by nested_model.channels *
 *                                                    *
 *                DO NOT EDIT THIS FILE               *
 *                                                    *
 * To rebuild it, run:                                *
 *                                                    *
 *     ./manage.py makefrontend [nested_model]        *
 *                                                    *
 ******************************************************/

import type { Unloaded } from '@rxdjango/react';

export interface User {
  _loaded: true;
  id: number;
  name: string;
  company: Company | Unloaded;
}

export interface Company {
  _loaded: true;
  id: number;
  name: string;
}