/**************************************************************
 * Generated by RxDjango on 2026-07-16 12:24 (UTC)            *
 *                                                            *
 * Based on all ContextChannel subclasses in testing.channels *
 *                                                            *
 *                    DO NOT EDIT THIS FILE                   *
 *                                                            *
 * To rebuild it, run:                                        *
 *                                                            *
 *     ./manage.py makefrontend [testing]                     *
 *                                                            *
 **************************************************************/

import { ContextChannel } from '@rxdjango/react';
import type { Task, VersionedCounter } from './testing.models';

const SOCKET_URL = (process.env.REACT_APP_RX_WEBSOCKET_URL ?? 'ws://localhost:8000') as string;

export class ListConvergenceChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/list/";
  protected baseURL: string = SOCKET_URL;

  items: number[] = [1, 2, 3];
  optional_items: number[] | null = null;

  do_append = async (value: number) => {
    return await this.rx.callAction('do_append', [value]);
  };

  do_insert = async (index: number, value: number) => {
    return await this.rx.callAction('do_insert', [index, value]);
  };

  do_setitem = async (index: number, value: number) => {
    return await this.rx.callAction('do_setitem', [index, value]);
  };

  do_delitem = async (index: number) => {
    return await this.rx.callAction('do_delitem', [index]);
  };

  do_remove = async (value: number) => {
    return await this.rx.callAction('do_remove', [value]);
  };

  do_pop = async () => {
    return await this.rx.callAction('do_pop', []);
  };

  do_extend = async (values: number[]) => {
    return await this.rx.callAction('do_extend', [values]);
  };

  do_iadd = async (values: number[]) => {
    return await this.rx.callAction('do_iadd', [values]);
  };

  do_clear = async () => {
    return await this.rx.callAction('do_clear', []);
  };

  do_sort = async () => {
    return await this.rx.callAction('do_sort', []);
  };

  do_reverse = async () => {
    return await this.rx.callAction('do_reverse', []);
  };

  do_imul = async (n: number) => {
    return await this.rx.callAction('do_imul', [n]);
  };

  do_slice_assign = async () => {
    return await this.rx.callAction('do_slice_assign', []);
  };

  do_slice_delete = async () => {
    return await this.rx.callAction('do_slice_delete', []);
  };

  do_reset = async (values: number[]) => {
    return await this.rx.callAction('do_reset', [values]);
  };

  do_burst = async () => {
    return await this.rx.callAction('do_burst', []);
  };

  do_append_optional = async (value: number) => {
    return await this.rx.callAction('do_append_optional', [value]);
  };

  do_set_optional = async (values: number[] | null) => {
    return await this.rx.callAction('do_set_optional', [values]);
  };

  do_wrong_type_append = async () => {
    return await this.rx.callAction('do_wrong_type_append', []);
  };
}

export class MemoTrackingChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/memo/";
  protected baseURL: string = SOCKET_URL;

  field_a: number = 0;
  field_b: number = 0;
  count_a: number = 0;
  count_b: number = 0;
  double_a: number = 0;
  double_b: number = 0;

  increment_a = async () => {
    return await this.rx.callAction('increment_a', []);
  };

  increment_b = async () => {
    return await this.rx.callAction('increment_b', []);
  };
}

export class ReconnectChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/reconnect/";
  protected baseURL: string = SOCKET_URL;

  tasks: Task[] | null = null;

  protected _modelFields: Record<string, {
      anchor: string;
      model: Record<string, Record<string, string>>;
      many?: boolean;
    }> = {
      "tasks": {
        anchor: "static_list.serializers.TaskSerializer",
        many: true,
        model: {
          "static_list.serializers.TaskSerializer": {  },
        },
      },
    };

  force_disconnect = async () => {
    return await this.rx.callAction('force_disconnect', []);
  };

  ping = async () => {
    return await this.rx.callAction('ping', []);
  };
}

export class TestingChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/";
  protected baseURL: string = SOCKET_URL;

  int_with_default: number = 1;
  int_optional: number | null = null;
  str_with_default: string = 'hello';
  str_optional: string | null = null;

  do_action = async (count: number, label: string) => {
    return await this.rx.callAction('do_action', [count, label]);
  };

  check_optionals_act_as_primitives_when_set = async () => {
    return await this.rx.callAction('check_optionals_act_as_primitives_when_set', []);
  };
}

export class VersionConsistencyChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/version/";
  protected baseURL: string = SOCKET_URL;

  counter: VersionedCounter | null = null;
  loaded: boolean = false;

  protected _modelFields: Record<string, {
      anchor: string;
      model: Record<string, Record<string, string>>;
      many?: boolean;
    }> = {
      "counter": {
        anchor: "testing.serializers.VersionedCounterSerializer",
        model: {
          "testing.serializers.VersionedCounterSerializer": {  },
        },
      },
    };
}
