/***************************************************
 * Generated by RxDjango on 2026-07-14 15:45 (UTC) *
 *                                                 *
 * Based on serializers used by testing.channels   *
 *                                                 *
 *              DO NOT EDIT THIS FILE              *
 *                                                 *
 * To rebuild it, run:                             *
 *                                                 *
 *     ./manage.py makefrontend [testing]          *
 *                                                 *
 ***************************************************/

export interface VersionedCounter {
  _loaded: true;
  id: number;
  value: number;
}