/***************************************************
 * Generated by RxDjango on 2026-07-16 12:24 (UTC) *
 *                                                 *
 * Based on serializers used by testing.channels   *
 *                                                 *
 *              DO NOT EDIT THIS FILE              *
 *                                                 *
 * To rebuild it, run:                             *
 *                                                 *
 *     ./manage.py makefrontend [testing]          *
 *                                                 *
 ***************************************************/

export interface Task {
  _loaded: true;
  id: number;
  name: string;
  status: string;
  priority: number;
  created_at: string;
}

export interface VersionedCounter {
  _loaded: true;
  id: number;
  value: number;
}