/**************************************************************
 * Generated by RxDjango on 2026-05-14 19:42 (UTC)            *
 *                                                            *
 * Based on all ContextChannel subclasses in testing.channels *
 *                                                            *
 *                    DO NOT EDIT THIS FILE                   *
 *                                                            *
 * To rebuild it, run:                                        *
 *                                                            *
 *     ./manage.py makefrontend [testing]                     *
 *                                                            *
 **************************************************************/

import { ContextChannel } from '@rxdjango/react';

const SOCKET_URL = (process.env.REACT_APP_RX_WEBSOCKET_URL ?? 'ws://localhost:8000') as string;

export class MemoTrackingChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/memo/";
  protected baseURL: string = SOCKET_URL;

  field_a: number = 0;
  field_b: number = 0;
  count_a: number = 0;
  count_b: number = 0;
  double_a: number = 0;
  double_b: number = 0;

  increment_a = async () => {
    return await this.rx.callAction('increment_a', []);
  };

  increment_b = async () => {
    return await this.rx.callAction('increment_b', []);
  };
}

export class TestingChannel extends ContextChannel {

  protected endpoint: string = "/ws/testing/";
  protected baseURL: string = SOCKET_URL;

  int_with_default: number = 1;
  int_optional: number | null = null;
  str_with_default: string = 'hello';
  str_optional: string | null = null;

  do_action = async (count: number, label: string) => {
    return await this.rx.callAction('do_action', [count, label]);
  };

  check_optionals_act_as_primitives_when_set = async () => {
    return await this.rx.callAction('check_optionals_act_as_primitives_when_set', []);
  };
}
