// @generated by tools/docgen — do not edit.
// Source: docs/
import type { ReactElement } from 'react';
import { OverviewPage as OverviewPage } from './pages/overview/Page';
import { QuickstartPage as QuickstartPage } from './pages/quickstart/Page';
import { ExamplesPage as ExamplesPage } from './pages/examples/Page';
import { CounterPage as ExamplesCounterPage } from './examples/counter/CounterPage';
import { CounterDemo } from './examples/counter/demo';
import { CarouselPage as ExamplesCarouselPage } from './examples/carousel/CarouselPage';
import { CarouselDemo } from './examples/carousel/demo';
import { MemoPage as ExamplesMemoPage } from './examples/memo/MemoPage';
import { MemoDemo } from './examples/memo/demo';
import { AuthorizationPage as ExamplesAuthorizationPage } from './examples/authorization/AuthorizationPage';
import { AuthorizationDemo } from './examples/authorization/demo';
import { AuthorizationMetaPage as ExamplesAuthorizationMetaPage } from './examples/authorization_meta/AuthorizationMetaPage';
import { AuthorizationMetaDemo } from './examples/authorization_meta/demo';
import { ProjectStatusPage as ProjectStatusPage } from './pages/project-status/Page';

export type Page = {
  slug: string;
  title: string;
  depth: number;
  parent: string | null;
  Component: () => ReactElement;
  Demo: (() => ReactElement) | null;
};

export const pages: Page[] = [
  { slug: 'overview', title: 'Overview', depth: 0, parent: null, Component: OverviewPage, Demo: null },
  { slug: 'quickstart', title: 'Quickstart', depth: 0, parent: null, Component: QuickstartPage, Demo: null },
  { slug: 'examples', title: 'Examples', depth: 0, parent: null, Component: ExamplesPage, Demo: null },
  { slug: 'examples/counter', title: 'Counter', depth: 1, parent: 'examples', Component: ExamplesCounterPage, Demo: CounterDemo },
  { slug: 'examples/carousel', title: 'Carousel', depth: 1, parent: 'examples', Component: ExamplesCarouselPage, Demo: CarouselDemo },
  { slug: 'examples/memo', title: 'Memo', depth: 1, parent: 'examples', Component: ExamplesMemoPage, Demo: MemoDemo },
  { slug: 'examples/authorization', title: 'Authorization', depth: 1, parent: 'examples', Component: ExamplesAuthorizationPage, Demo: AuthorizationDemo },
  { slug: 'examples/authorization_meta', title: 'Authorization Meta', depth: 1, parent: 'examples', Component: ExamplesAuthorizationMetaPage, Demo: AuthorizationMetaDemo },
  { slug: 'project-status', title: 'Project status', depth: 0, parent: null, Component: ProjectStatusPage, Demo: null },
];
