// @generated by tools/docgen — do not edit.
// Source: docs/
import type { ReactElement } from 'react';
import { OverviewPage as OverviewPage } from './pages/overview/Page';
import { QuickstartPage as QuickstartPage } from './pages/quickstart/Page';
import { ExamplesPage as ExamplesPage } from './pages/examples/Page';
import { CounterPage as ExamplesCounterPage } from './examples/counter/CounterPage';
import { CounterDemo } from './examples/counter/demo';
import { CarouselPage as ExamplesCarouselPage } from './examples/carousel/CarouselPage';
import { CarouselDemo } from './examples/carousel/demo';
import { MemoPage as ExamplesMemoPage } from './examples/memo/MemoPage';
import { MemoDemo } from './examples/memo/demo';
import { AuthorizationPage as ExamplesAuthorizationPage } from './examples/authorization/AuthorizationPage';
import { AuthorizationDemo } from './examples/authorization/demo';
import { AuthorizationMetaPage as ExamplesAuthorizationMetaPage } from './examples/authorization_meta/AuthorizationMetaPage';
import { AuthorizationMetaDemo } from './examples/authorization_meta/demo';
import { SimpleModelPage as ExamplesSimpleModelPage } from './examples/simple_model/SimpleModelPage';
import { SimpleModelDemo } from './examples/simple_model/demo';
import { NestedModelPage as ExamplesNestedModelPage } from './examples/nested_model/NestedModelPage';
import { NestedModelDemo } from './examples/nested_model/demo';
import { ReactiveModelPage as ExamplesReactiveModelPage } from './examples/reactive_model/ReactiveModelPage';
import { ReactiveModelDemo } from './examples/reactive_model/demo';
import { ScalarListPage as ExamplesScalarListPage } from './examples/scalar_list/ScalarListPage';
import { ScalarListDemo } from './examples/scalar_list/demo';
import { ListTypesPage as ExamplesListTypesPage } from './examples/list_types/ListTypesPage';
import { ListTypesDemo } from './examples/list_types/demo';
import { StreamingListPage as ExamplesStreamingListPage } from './examples/streaming_list/StreamingListPage';
import { StreamingListDemo } from './examples/streaming_list/demo';
import { StaticListPage as ExamplesStaticListPage } from './examples/static_list/StaticListPage';
import { StaticListDemo } from './examples/static_list/demo';
import { ProjectStatusPage as ProjectStatusPage } from './pages/project-status/Page';

export type Page = {
  slug: string;
  title: string;
  depth: number;
  parent: string | null;
  Component: () => ReactElement;
  Demo: (() => ReactElement) | null;
};

export const pages: Page[] = [
  { slug: 'overview', title: 'Overview', depth: 0, parent: null, Component: OverviewPage, Demo: null },
  { slug: 'quickstart', title: 'Quickstart', depth: 0, parent: null, Component: QuickstartPage, Demo: null },
  { slug: 'examples', title: 'Examples', depth: 0, parent: null, Component: ExamplesPage, Demo: null },
  { slug: 'examples/counter', title: 'Basic channel', depth: 1, parent: 'examples', Component: ExamplesCounterPage, Demo: CounterDemo },
  { slug: 'examples/carousel', title: 'rx fields', depth: 1, parent: 'examples', Component: ExamplesCarouselPage, Demo: CarouselDemo },
  { slug: 'examples/memo', title: '@memo', depth: 1, parent: 'examples', Component: ExamplesMemoPage, Demo: MemoDemo },
  { slug: 'examples/authorization', title: 'Authorization', depth: 1, parent: 'examples', Component: ExamplesAuthorizationPage, Demo: AuthorizationDemo },
  { slug: 'examples/authorization_meta', title: 'Authorization Meta', depth: 1, parent: 'examples', Component: ExamplesAuthorizationMetaPage, Demo: AuthorizationMetaDemo },
  { slug: 'examples/simple_model', title: 'Simple model', depth: 1, parent: 'examples', Component: ExamplesSimpleModelPage, Demo: SimpleModelDemo },
  { slug: 'examples/nested_model', title: 'Nested model', depth: 1, parent: 'examples', Component: ExamplesNestedModelPage, Demo: NestedModelDemo },
  { slug: 'examples/reactive_model', title: 'Reactive model', depth: 1, parent: 'examples', Component: ExamplesReactiveModelPage, Demo: ReactiveModelDemo },
  { slug: 'examples/scalar_list', title: 'Reactive list of scalars', depth: 1, parent: 'examples', Component: ExamplesScalarListPage, Demo: ScalarListDemo },
  { slug: 'examples/list_types', title: 'Union and optional list elements', depth: 1, parent: 'examples', Component: ExamplesListTypesPage, Demo: ListTypesDemo },
  { slug: 'examples/streaming_list', title: 'Streaming list updates', depth: 1, parent: 'examples', Component: ExamplesStreamingListPage, Demo: StreamingListDemo },
  { slug: 'examples/static_list', title: 'Static list', depth: 1, parent: 'examples', Component: ExamplesStaticListPage, Demo: StaticListDemo },
  { slug: 'project-status', title: 'Project status', depth: 0, parent: null, Component: ProjectStatusPage, Demo: null },
];
