/******************************************************
 * Generated by RxDjango on 2026-05-14 12:23 (UTC)    *
 *                                                    *
 * Based on serializers used by simple_model.channels *
 *                                                    *
 *                DO NOT EDIT THIS FILE               *
 *                                                    *
 * To rebuild it, run:                                *
 *                                                    *
 *     ./manage.py makefrontend [simple_model]        *
 *                                                    *
 ******************************************************/

export interface User {
  name: string;
}