/******************************************************************
 * Generated by RxDjango on 2026-05-12 (UTC)                       *
 *                                                                 *
 * Based on all ContextChannel subclasses in simple_model.channels *
 *                                                                 *
 *                      DO NOT EDIT THIS FILE                      *
 *                                                                 *
 * To rebuild it, run:                                             *
 *                                                                 *
 *     ./manage.py makefrontend [simple_model]                     *
 *                                                                 *
 ******************************************************************/

import { ContextChannel } from '@rxdjango/react';

const SOCKET_URL = "ws://localhost:8000";

export interface User {
  name: string;
}

export class AuthorizationChannel extends ContextChannel {

  protected endpoint: string = "/ws/simple_model/";
  protected baseURL: string = SOCKET_URL;

  user: User | null = null;

  authorize = async (password: string) => {
    return await this.rx.callAction('authorize', [password]);
  };
}
