/*********************************************************
 * Generated by RxDjango on 2026-07-16 17:04 (UTC)       *
 *                                                       *
 * Based on serializers used by static_queryset.channels *
 *                                                       *
 *                 DO NOT EDIT THIS FILE                 *
 *                                                       *
 * To rebuild it, run:                                   *
 *                                                       *
 *     ./manage.py makefrontend [static_queryset]        *
 *                                                       *
 *********************************************************/

export interface Task {
  _loaded: true;
  id: number;
  name: string;
  status: string;
  priority: number;
  created_at: string;
}