# Generated by Django 6.0.5 on 2026-05-12 14:57

from django.db import migrations


def forwards(apps, schema):
    User = apps.get_model('simple_model', 'User')
    User.objects.create(id=1, name='Registered User')


def backwards(apps, schema):
    User = apps.get_model('simple_model', 'User')
    try:
        User.objects.get(id=1).delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('simple_model', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
