// @generated by tools/docgen — do not edit.
// Source: docs/examples/index.md (toctree order)
import type { ReactElement } from 'react';
import { CounterPage } from './counter/CounterPage';
import { CarouselPage } from './carousel/CarouselPage';
import { MemoPage } from './memo/MemoPage';
import { AuthorizationPage } from './authorization/AuthorizationPage';
import { AuthorizationMetaPage } from './authorization_meta/AuthorizationMetaPage';

export type Page = [app: string, title: string, Component: () => ReactElement];

export const pages: Page[] = [
  ['counter', 'Counter', CounterPage],
  ['carousel', 'Carousel', CarouselPage],
  ['memo', 'Memo', MemoPage],
  ['authorization', 'Authorization', AuthorizationPage],
  ['authorization_meta', 'Authorization Meta', AuthorizationMetaPage],
];
