// @generated by tools/docgen — do not edit.
// Source: docs/quickstart.md

import React from 'react';

export function QuickstartPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Quickstart
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        Install the Python package and the React client: bash pip install rxdjango npm install @rxdjango/react  Define a channel on the backend, expose it over the ASGI router, and subscribe from React with useChannel. The [Examples](examples/index.md) section shows full working channels you can copy.
      </p>
    </div>
  );
}

export default QuickstartPage;
