// @generated by tools/docgen — do not edit.
// Source: docs/quickstart.md

import React from 'react';

export function QuickstartPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Quickstart
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        This section will contain a guide on how to setup RxDjango. For now, check the examples backend project in source code at [Github](https://github.com/rxdjango/rxdjango).
      </p>
    </div>
  );
}

export default QuickstartPage;
