from __future__ import annotations

from collections import defaultdict
from typing import Any, Generator, Iterator

from rest_framework import serializers
from django.db import ProgrammingError
from django.db.models import Model
from django.db.models.fields import related_descriptors
from .typescript import export_interface
from .exceptions import UnknownProperty
from .related_properties import is_related_property, get_accessor, get_reverse_accessor


class StateModel:
    """The StateModel is constructed based on a nested serializers.ModelSerializer
    instance. It introspects the serializer and recursively build a model with all
    layers of the serializer.
    """

    def __init__(self, state_serializer: serializers.ModelSerializer, many: bool = False, origin: StateModel | None = None) -> None:
        self.nested_serializer = state_serializer
        self.many = many
        self.origin = origin

        if origin is None:
            # This is the top-most call
            self.index = defaultdict(list)
        else:
            self.index = origin.index

        try:
            meta = state_serializer.Meta
        except AttributeError:
            meta = state_serializer.child.Meta

        self.model = meta.model

        self.instance_type = '.'.join([
            self.nested_serializer.__module__,
            self.nested_serializer.__class__.__name__,
        ])

        self.index[self.instance_type].append(self)

        self.flat_serializer, fields = self._disassemble_nested()

        self.children = {}
        for field_name, serializer in fields.items():
            node = self._build_child(field_name, serializer)
            if node:
                self.children[field_name] = node

        export_interface(self.nested_serializer.__class__)

    def __str__(self) -> str:
        return f'StateModel for {self.instance_type}'

    def __repr__(self) -> str:
        return str(self)

    def __getitem__(self, key: str) -> StateModel:
        return self.children[key]

    def models(self) -> Iterator[StateModel]:
        for nodes in self.index.values():
            for model in nodes:
                yield model

    def frontend_model(self) -> dict[str, dict[str, str]]:
        """This is the field definition to be serialized inside the frontend
        channel field definition.
        """
        frontend = {}
        for key, nodes in self.index.items():
            node = nodes[0]
            instance_model = {}
            frontend[key] = instance_model
            serializer = node.nested_serializer
            for field_name, field in serializer._declared_fields.items():
                if is_model_serializer(field):
                    instance_model[field_name] = node[field_name].instance_type

        return frontend

    def serialize_instance(self, instance: Model) -> dict[str, Any]:
        """This will be used by post_save signal to serialize a single instance"""
        data = self.flat_serializer(instance).data
        data['_type'] = self.instance_type
        return data

    def serialize_delete(self, instance: Model) -> dict[str, Any]:
        """This will be used by post_delete signal to serialize a single instance"""
        return {
            '_type': self.instance_type
            '_del': instance.pk or instance.id
        }

    def serialize_state(self, instance: Model) -> Generator[list[dict[str, Any]], None, None]:
        """Serialize a nested instance into a series of flat serialized instances that
        can be rebuilt by the frontend using the model generated by frontend_model().
        """
        if self.many:
            data = self.flat_serializer(instance.all(), many=True).data
            instances = instance.all()
        else:
            data = [self.flat_serializer(instance).data]
            instances = [instance]

        for serialized in data:
            serialized['_type'] = self.instance_type

        yield data

        for field_name, peer_model in self.children.items():
            for instance in instances:
                try:
                    peer_instance = getattr(instance, field_name)
                except AttributeError:
                    continue
                if peer_instance is None:
                    continue
                for serialized in peer_model.serialize_state(peer_instance, tstamp):
                    yield serialized

    def _disassemble_nested(self) -> tuple[type[serializers.ModelSerializer], dict[str, serializers.BaseSerializer]]:
        serializer_fields = {}
        declared_fields = {}

        for field_name in self.nested_serializer.fields.keys():
            field = self.nested_serializer._declared_fields.get(field_name)

            if field is None:
                continue

            if is_related_property(self.model, field_name):
                try:
                    new_field = serializers.PrimaryKeyRelatedField(
                        many=field.many, read_only=True,
                    )
                except AttributeError:
                    new_field = serializers.PrimaryKeyRelatedField(
                        read_only=True,
                    )
                serializer_fields[field_name] = field
                declared_fields[field_name] = new_field
            elif is_model_serializer(field):
                serializer_fields[field_name] = field
            else:
                declared_fields[field_name] = field

        # Return the new flat serializer class and the dictionary of substituted fields
        FlatSerializer = type(
            self.nested_serializer.__class__.__name__,
            (serializers.ModelSerializer,),
            {
                "Meta": self.nested_serializer.Meta,
                **declared_fields,
            }
        )

        return FlatSerializer, serializer_fields

    def _build_child(self, field_name: str, serializer: serializers.BaseSerializer) -> StateModel | None:
        try:
            descriptor = getattr(self.model, field_name)
        except AttributeError:
            return

        if isinstance(descriptor, related_descriptors.ManyToManyDescriptor):
            related_descriptor = getattr(descriptor.field.model, descriptor.field.name)
            return StateModel(
                serializer.child,
                None,
                True,
            )

        if isinstance(descriptor, related_descriptors.ReverseManyToOneDescriptor):
            related_descriptor = getattr(descriptor.field.model, descriptor.field.name)
            return StateModel(
                serializer.child,
                None,
                True,
            )

        if isinstance(descriptor, related_descriptors.ForwardManyToOneDescriptor):
            return StateModel(
                serializer,
                None,
                False,
            )

        if isinstance(descriptor, related_descriptors.ReverseOneToOneDescriptor):
            return StateModel(
                serializer,
                None,
                False,
            )


def is_model_serializer(field: serializers.BaseSerializer) -> bool:
    try:
        return isinstance(field.child, serializers.ModelSerializer)
    except AttributeError:
        return isinstance(field, serializers.ModelSerializer)
