/****************************************************
 * Generated by RxDjango on 2026-07-16 14:11 (UTC)  *
 *                                                  *
 * Based on serializers used by task_board.channels *
 *                                                  *
 *               DO NOT EDIT THIS FILE              *
 *                                                  *
 * To rebuild it, run:                              *
 *                                                  *
 *     ./manage.py makefrontend [task_board]        *
 *                                                  *
 ****************************************************/

export interface Task {
  _loaded: true;
  id: number;
  name: string;
  status: string;
  priority: number;
  project_id: number;
  created_at: string;
}