// @generated by tools/docgen — do not edit.
// Source: docs/examples/carousel.md

import React from 'react';
import { CarouselDemo } from './demo';
import {
  ExampleLayout,
  ExampleSection,
  ExampleSectionHeading,
  ExampleDescription,
  ExampleClientBadge,
} from '../../components/ExampleLayout';
import { SourceFile } from '../../components/SourceFile';

export function CarouselPage() {
  return (
    <ExampleLayout title="Carousel" demo={<CarouselDemo />}>
      <ExampleSection position="first">
        <ExampleDescription>
          Three related reactive fields—selected index, fruit name, and first letter—updated together when you call rotate. Shows how the backend can keep a small graph of state consistent in one action.
        </ExampleDescription>
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-carousel-backend">
        <ExampleSectionHeading id="examples-carousel-backend">
          Backend
        </ExampleSectionHeading>
        <SourceFile path="carousel/channels.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-carousel-frontend" position="last">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <ExampleSectionHeading id="examples-carousel-frontend">
            Frontend
          </ExampleSectionHeading>
          <ExampleClientBadge />
        </div>
        <SourceFile path="carousel/demo.tsx" />
      </ExampleSection>
    </ExampleLayout>
  );
}

export default CarouselPage;
