/********************************************************
 * Generated by RxDjango on 2026-05-15 10:08 (UTC)      *
 *                                                      *
 * Based on serializers used by reactive_model.channels *
 *                                                      *
 *                 DO NOT EDIT THIS FILE                *
 *                                                      *
 * To rebuild it, run:                                  *
 *                                                      *
 *     ./manage.py makefrontend [reactive_model]        *
 *                                                      *
 ********************************************************/

export interface Task {
  id: number;
  name: string;
  project: Project;
}

export interface Project {
  id: number;
  name: string;
}