/********************************************************
 * Generated by RxDjango on 2026-07-14 15:45 (UTC)      *
 *                                                      *
 * Based on serializers used by reactive_model.channels *
 *                                                      *
 *                 DO NOT EDIT THIS FILE                *
 *                                                      *
 * To rebuild it, run:                                  *
 *                                                      *
 *     ./manage.py makefrontend [reactive_model]        *
 *                                                      *
 ********************************************************/

import type { Unloaded } from '@rxdjango/react';

export interface Task {
  _loaded: true;
  id: number;
  name: string;
  project: Project | Unloaded;
}

export interface Project {
  _loaded: true;
  id: number;
  name: string;
}