// @generated by tools/docgen — do not edit.
// Source: docs/project-status.md

import React from 'react';

export function ProjectStatusPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Project status
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        RxDjango is being rebuilt from the v0.0.x prototype that lives at [rxdjango/rxdjango-0](https://github.com/rxdjango/rxdjango). The current focus is the semantics — serializers, channels, and the Python↔TypeScript boundary — rather than transport plumbing. Track ongoing work via the ADRs under docs/adr/ and the issues on the GitHub repository.
      </p>
    </div>
  );
}

export default ProjectStatusPage;
