// @generated by tools/docgen — do not edit.
// Source: docs/overview.md

import React from 'react';

export function OverviewPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Overview
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        In Django, Python code is the source of truth for the database: models declare the schema, and everything else follows. RxDjango extends that principle to real-time single-page applications: channels declare the live state a client sees, and a typed TypeScript SDK follows. A channel is a Python class — a ContextChannel — declared in a channels.py file inside a Django app. It holds the state of one client connection: plain reactive values, computed fields, or model instances serialized with the DRF serializers you already write. From these declarations RxDjango generates a matching TypeScript class for the frontend. At runtime, each connected client gets a live instance of the channel. Assigning to a field on the server pushes the new value to the frontend automatically, and the frontend calls the channel's actions like ordinary async methods — no hand-written consumers, no channel groups, no message routing on either side. See the <a href={`${process.env.PUBLIC_URL || ''}/quickstart`} className="text-primary-700 hover:underline">Quickstart</a> for setup, and try the <a href={`${process.env.PUBLIC_URL || ''}/examples`} className="text-primary-700 hover:underline">Examples</a> to interact with each feature live.
      </p>
    </div>
  );
}

export default OverviewPage;
