// @generated by tools/docgen — do not edit.
// Source: docs/overview.md

import React from 'react';

export function OverviewPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Overview
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        In Django, Python code is the source of truth for databases. RxDjango extends this principle to generate SDKs for real-time single page applications (SPAs). Developer declares ContextChannel classes in channels.py file inside each app. For each context channel, a matching Typescript class is created. The Python instance of the channel holds the context in memory, and updates are automatically forward to the frontend's state. Frontend can call methods directly using RPC, with a matching interface for the backend class. See the <a href={`${process.env.PUBLIC_URL || ''}/quickstart`} className="text-primary-700 hover:underline">Quickstart</a> for setup and check the <a href={`${process.env.PUBLIC_URL || ''}/examples`} className="text-primary-700 hover:underline">Examples</a> on how it works.
      </p>
    </div>
  );
}

export default OverviewPage;
