// @generated by tools/docgen — do not edit.
// Source: docs/overview.md

import React from 'react';

export function OverviewPage() {
  return (
    <div className="mx-auto w-full max-w-3xl flex-1 overflow-y-auto px-6 py-10">
      <h1 className="text-2xl font-semibold tracking-tight text-ink">
        Overview
      </h1>
      <p className="mt-4 max-w-prose text-base leading-relaxed text-primary-800">
        RxDjango exposes Django models and actions as reactive channels. A client subscribes to a channel, receives a typed initial state, and then receives diffs as the server-side state changes. Actions are plain methods on the channel class. This page will grow into a guided tour. For now, see the [Quickstart](quickstart.md) for the minimal setup and [Examples](examples/index.md) for runnable demos.
      </p>
    </div>
  );
}

export default OverviewPage;
