/*****************************************************
 * Generated by RxDjango on 2026-07-16 12:18 (UTC)   *
 *                                                   *
 * Based on serializers used by static_list.channels *
 *                                                   *
 *               DO NOT EDIT THIS FILE               *
 *                                                   *
 * To rebuild it, run:                               *
 *                                                   *
 *     ./manage.py makefrontend [static_list]        *
 *                                                   *
 *****************************************************/

export interface Task {
  _loaded: true;
  id: number;
  name: string;
  status: string;
  priority: number;
  created_at: string;
}