/*************************************************************************
 * Generated by RxDjango on 2026-05-11 20:02 (UTC)                       *
 *                                                                       *
 * Based on all ContextChannel subclasses in authorization_meta.channels *
 *                                                                       *
 *                         DO NOT EDIT THIS FILE                         *
 *                                                                       *
 * To rebuild it, run:                                                   *
 *                                                                       *
 *     ./manage.py makefrontend [authorization_meta]                     *
 *                                                                       *
 *************************************************************************/

import { ContextChannel } from '@rxdjango/react';

const SOCKET_URL = "ws://localhost:8000";

export class AuthorizationMetaChannel extends ContextChannel {

  protected endpoint: string = "/ws/authorization_meta/";
  protected baseURL: string = SOCKET_URL;

  counter: number = 0;

  authorize = async (password: string) => {
    return await this.rx.callAction('authorize', [password]);
  };

  increment = async () => {
    return await this.rx.callAction('increment', []);
  };
}
