// @generated by tools/docgen — do not edit.
// Source: docs/examples/static_list.md

import React from 'react';
import { StaticListDemo } from './demo';
import {
  ExampleLayout,
  ExampleSection,
  ExampleSectionHeading,
  ExampleDescription,
  ExampleClientBadge,
} from '../../components/ExampleLayout';
import { SourceFile } from '../../components/SourceFile';

export function StaticListPage() {
  return (
    <ExampleLayout title="Static list" demo={<StaticListDemo />}>
      <ExampleSection position="first">
        <ExampleDescription>
          Demonstrates the static-queryset-lists tier: tasks is a bare Django queryset assigned once in on_connect to a many=True rx.model field -- no declaration language, no new verbs. Membership is derived entirely on the client: the snapshot's rows, filtered by the queryset's conditions and sorted by its ordering, both re-evaluated live as ordinary update frames arrive. Toggling a task's status flips it out of (or back into) the list; raising its priority re-sorts it; deleting it removes it. A task created after the snapshot does not appear until the field is rebound -- the static tier's one deliberate limitation (no live new-row delivery; that arrives with the routed tier).
        </ExampleDescription>
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-static-list-backend">
        <ExampleSectionHeading id="examples-static-list-backend">
          Backend
        </ExampleSectionHeading>
        <SourceFile path="static_list/channels.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-static-list-models">
        <ExampleSectionHeading id="examples-static-list-models">
          Models
        </ExampleSectionHeading>
        <SourceFile path="static_list/models.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-static-list-serializers">
        <ExampleSectionHeading id="examples-static-list-serializers">
          Serializers
        </ExampleSectionHeading>
        <SourceFile path="static_list/serializers.py" />
      </ExampleSection>
      <ExampleSection ariaLabelledBy="examples-static-list-frontend" position="last">
        <div className="flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between">
          <ExampleSectionHeading id="examples-static-list-frontend">
            Frontend
          </ExampleSectionHeading>
          <ExampleClientBadge />
        </div>
        <SourceFile path="static_list/demo.tsx" />
      </ExampleSection>
    </ExampleLayout>
  );
}

export default StaticListPage;
