# Generated by Django 6.0.5 on 2026-05-15 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactive_model', '0002_create_sample_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='_v',
            field=models.BigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='_v',
            field=models.BigIntegerField(default=0, editable=False),
        ),
    ]
